### ISSUE TITLE
Looks like HA 2022.10 is breaking this component again

### ISSUE THREAD

**Issue by DavidFW1960** [Limych/ha-average#158]
**Environment**

- Home Assistant Core release with the issue: 2022.10.x
- This custom component release with the issue: current
- Last working this custom component release (if known):
- Operating environment (Home Assistant/Supervisor/Docker/venv):

**Describe the bug**

**Configuration.yaml**
```yaml

Add your configs here if any.

```

**Steps to Reproduce**

**Expected behavior**

**Debug log**

``2022-09-16 12:23:58.264 WARNING (SyncWorker_1) [homeassistant.helpers.frame] Detected integration that accesses the database without the database executor; Use homeassistant.components.recorder.get_instance(hass).async_add_executor_job() for faster database operations. Please report issue to the custom integration author for average using this method at custom_components/average/sensor.py, line 477: history_list = history.state_changes_during_period(
2022-09-16 12:23:58.602 ERROR (MainThread) [homeassistant.helpers.entity] Update for sensor.today_temp_bom fails
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 515, in async_update_ha_state
await self.async_device_update()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 710, in async_device_update
raise exc
File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
result = self.fn(*self.args, **self.kwargs)
File "/usr/src/homeassistant/homeassistant/util/__init__.py", line 192, in wrapper
result = method(*args, **kwargs)
File "/config/custom_components/average/sensor.py", line 305, in update
self._update_state()
File "/config/custom_components/average/sensor.py", line 491, in _update_state
item = history.get_state(self.hass, start, entity_id)
AttributeError: module 'homeassistant.components.recorder.history' has no attribute 'get_state'
```

**Additional context**
<!--
  Add any other context about the problem here.
-->

**Comment by lmagyar** [comment]
I didn't update to core 2022.10.x because of this issue. Is the average sensor unusable again with the released core 2022.10.x?
