### ISSUE TITLE
Proper value for "undefined values (unavailable, sensor undefined, etc.)"

### ISSUE THREAD

**Issue by deepcoder** [Limych/ha-average#18]
Proper value for "undefined values (unavailable, sensor undefined, etc.)"

Great work on your sensor, thanks!

What is the expected 'value' for a sensor attribute that is not 'correct'. I am creating some MQTT sensors that publish JSON attributes. When the sensor returns an error, I publish JSON with attributes to indicate an error. However I do not publish the attribute that I am using as an input to your average sensor. This returns the error below in the HA log:

2020-10-12 19:44:57 ERROR (MainThread) [custom_components.average.sensor] Could not convert value "" to float

**Versions**

* Version of the Home Assistant: 0.115.6
* Version of the custom component:  'release/1.6.5'

**Configuration**
```yaml

Add your configs here.

```

**Describe the bug**

**To Reproduce**

If applicable, describe the steps to reproduce the behavior:

**Expected behavior**

**Screenshots**

**Debug log**

```text

Add your logs here.

```

**Additional context**

**Comment by Limych** [comment]
I cannot reproduce your bug, and as a result, I cannot fix it. Try using a fresh version of the component where a similar bug has been fixed. If this does not help, please fill in the bug report completely in accordance with the template given to you.

**Comment by klatka** [comment]
I think thats the same problem. The source of the avg sensor is from jseidl/hass-magic_areas and the init values are `None`.
Following errors occured:

```
Logger: homeassistant.helpers.event
Source: custom_components/average/sensor.py:260
First occurred: 9:10:54 (5 occurrences)
Last logged: 9:14:19

Error while processing state changed for sensor.area_temperature_ankleidezimmer
Error while processing state changed for sensor.area_temperature_flur
Error while processing state changed for sensor.area_temperature_schlafzimmer
Error while processing state changed for sensor.area_temperature_abstellkammer
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/event.py", line 257, in _async_state_change_dispatcher
    hass.async_run_hass_job(job, event)
  File "/usr/src/homeassistant/homeassistant/core.py", line 434, in async_run_hass_job
    hassjob.target(*args)
  File "/usr/src/homeassistant/homeassistant/helpers/event.py", line 198, in state_change_listener
    hass.async_run_hass_job(
  File "/usr/src/homeassistant/homeassistant/core.py", line 434, in async_run_hass_job
    hassjob.target(*args)
  File "/config/custom_components/average/sensor.py", line 209, in sensor_state_listener
    self._update_state()
  File "/config/custom_components/average/sensor.py", line 447, in _update_state
    value = self._get_entity_state(entity)
  File "/config/custom_components/average/sensor.py", line 275, in _get_entity_state
    self._get_temperature(entity) if self._temperature_mode else entity.state
  File "/config/custom_components/average/sensor.py", line 260, in _get_temperature
    raise ValueError(
ValueError: None is not a recognized temperature unit.
```

All of the `sensor.area_temperature_x` have a valid value after few moments but the average sensor is still unavailable...
