### ISSUE TITLE
ValueError: None is not a recognized temperature unit.

### ISSUE THREAD

**Issue by klatka** [Limych/ha-average#21]
**Versions**

* Version of the Home Assistant: 0.118.4
* Version of the custom component: 1.6.5

**Configuration**
```yaml

- platform: average
  name: 'Interior Temperature 1h'
  duration:
    hours: 1
  entities:
    - sensor.interior_temperature

```
`sensor.interior_temperature` has the following output:
```
sensors:
  - sensor.temperature1
  - sensor.temperature2
  - ...
unit_of_measurement: °C
friendly_name: Interior Temperature
device_class: temperature
```

**Describe the bug**

`unit_of_measurement` of source sensor is not recognized correctly. Avg sensor value is unavailable.

**To Reproduce**

If applicable, describe the steps to reproduce the behavior:

**Expected behavior**

Avg output of last hour of source sensor.

**Screenshots**

**Debug log**

```text

Logger: homeassistant.helpers.entity
Source: custom_components/average/sensor.py:260
First occurred: 0:03:46 (15 occurrences)
Last logged: 0:10:34

Update for sensor.interior_temperature_1h fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 278, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 474, in async_device_update
    raise exc
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/homeassistant/homeassistant/util/__init__.py", line 239, in wrapper
    result = method(*args, **kwargs)
  File "/config/custom_components/average/sensor.py", line 299, in update
    self._update_state()
  File "/config/custom_components/average/sensor.py", line 477, in _update_state
    current_state = self._get_entity_state(item)
  File "/config/custom_components/average/sensor.py", line 275, in _get_entity_state
    self._get_temperature(entity) if self._temperature_mode else entity.state
  File "/config/custom_components/average/sensor.py", line 260, in _get_temperature
    raise ValueError(
ValueError: None is not a recognized temperature unit.

```

**Additional context**

**Comment by Limych** [comment]
Please, update component to the latest version.
