### ISSUE TITLE
HACS Has faulty download url for release 2.3.1

### ISSUE THREAD

**Issue by FloSeidel** [Limych/ha-average#220]
### Checklist

- [X] I have filled out the template to the best of my ability.
- [X] This only contains 1 feature request (if you have multiple feature requests, open one feature request for each feature request).
- [X] This issue is not a duplicate feature request of [previous feature requests](https://github.com/ludeeus/integration_blueprint/issues?q=is%3Aissue+label%3A%22Feature+Request%22+).

### Is your feature request related to a problem? Please describe.

A download of version 2.3.1 via HACS does not seem to be possible for me. For some reason the download url is wrong. The release zip file is called `average.zip`. HACS tries to download `https://github.com/Limych/ha-average/releases/download/tags/2.3.1/average_sensor.zip`

```
2024-01-22 21:55:50.272 ERROR (MainThread) [custom_components.hacs] <Integration Limych/ha-average> Failed to download https://github.com/Limych/ha-average/releases/download/tags/2.3.1/average_sensor.zip
2024-01-22 21:55:50.273 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [139846613747136] Error handling message: Unknown error (unknown_error) <username> from <ip> (Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:121.0) Gecko/20100101 Firefox/121.0)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 26, in _handle_async_response
    await func(hass, connection, msg)
  File "/config/custom_components/hacs/websocket/repository.py", line 234, in hacs_repository_download
    await repository.async_install()
  File "/config/custom_components/hacs/repositories/base.py", line 893, in async_install
    await self.async_install_repository(version=version)
  File "/config/custom_components/hacs/repositories/base.py", line 990, in async_install_repository
    raise HacsException("Could not download, see log for details")
custom_components.hacs.exceptions.HacsException: Could not download, see log for details
```

### Describe the solution you'd like

I would like to have access to the most recent release via HACS.

### Describe alternatives you've considered

An alternative would be to download the sources directly and install the version manually. In order to make sure to get the next update I would prefer installing via HACS. What did work was the download of Version `2.3.0`.

### Additional context

Core:  2024.1.5
Supervisor: 2023.12.1
Operating System: 11.4
Frontend: 20240104.0

**Comment by tompipe** [comment]
I'm seeing the same issue. Looks like its caused by the following:

https://github.com/Limych/ha-average/blob/803639f5cd7d0e33d7c911b8b2b4c09aa0c06d4b/hacs.json#L3

Yet the package is being named ```average.zip``` by github actions, which uses the directory name:

https://github.com/Limych/ha-average/blob/803639f5cd7d0e33d7c911b8b2b4c09aa0c06d4b/.github/workflows/release.yml#L17-L19

and zipped using

https://github.com/Limych/ha-average/blob/803639f5cd7d0e33d7c911b8b2b4c09aa0c06d4b/.github/workflows/release.yml#L31-L35
