### ISSUE TITLE
Average over time period fails

### ISSUE THREAD

**Issue by mattsmallman** [Limych/ha-average#24]
**Versions**

* Version of the Home Assistant: 2021.1.2
* Version of the custom component: 1.6.6

**Configuration**
```yaml

- platform: average
  name: Bedroom Average Overnight Temperature
  start: '{{ as_timestamp( now().replace(hour=23).replace(minute=0).replace(second=0) ) - 86400 }}'
  duration:
    hours: 8
  entities:
    - sensor.bedroom_sensor_temperature

```

**Describe the bug**

I have several average sensors to assess environmental factors that might impact sleep quality so average from 11 pm to 7am. These all worked for many months but after a HASS release (aprox 17 Dec - but don't know exactly which version as I am usually take a few days to update) they all fail with this error. I have tried various different timestamp and date time configurations but without success. 

**To Reproduce**

n/a

**Expected behavior**

Average temperature from 11pm last night to 7am this morning.

**Screenshots**

n/a

**Debug log**

```text

Logger: homeassistant.helpers.entity
Source: util/dt.py:131 
First occurred: 22:01:22 (4 occurrences) 
Last logged: 22:02:47

Update for sensor.bedroom_average_overnight_temperature fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 278, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 474, in async_device_update
    raise exc
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/homeassistant/homeassistant/util/__init__.py", line 239, in wrapper
    result = method(*args, **kwargs)
  File "/config/custom_components/average/sensor.py", line 280, in update
    self._update_state()
  File "/config/custom_components/average/sensor.py", line 369, in _update_state
    self._update_period()
  File "/config/custom_components/average/sensor.py", line 305, in _update_period
    start = dt_util.parse_datetime(start_rendered)
  File "/usr/src/homeassistant/homeassistant/util/dt.py", line 131, in parse_datetime
    return ciso8601.parse_datetime(dt_str)
TypeError: argument 1 must be str, not float

```

**Additional context**

First ever GitHub Issue so please be gentle and let me know if you need more context.

**Comment by Limych** [comment]
Thank you for bugreport
