### ISSUE TITLE
ZeroDivisionError: division by zero when calculating the average.

### ISSUE THREAD

**Issue by niemyjski** [Limych/ha-average#3]
I have multiple sensors going into an average and I have been getting the following in my logs on 0.99.2.

![image](https://user-images.githubusercontent.com/1020579/65560028-aa346580-df02-11e9-91a7-7565395cc4b0.png)

```text
Update for sensor.average_inside_temperature fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 261, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 439, in async_device_update
    await self.async_update()
  File "/config/custom_components/average/sensor.py", line 283, in async_update
    value /= elapsed
ZeroDivisionError: division by zero
```

**Comment by niemyjski** [comment]
Thank you!
