### ISSUE TITLE
Unavailable (again) 

### ISSUE THREAD

**Issue by mf-social** [Limych/ha-average#5]
## Configuration

```yaml
- platform: average
  name: Average light level
  entities:
    - sensor.bathroom_light_level
    - sensor.landing_light_level
    - sensor.kitchen_light_level
```

## Describe the bug

Sensor value shows as Unknown

## Debug log

```text

Exception in callback async_track_state_change.<locals>.state_change_listener(<Event state_...053304+01:00>>) at /usr/src/homeassistant/homeassistant/helpers/event.py:76
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/src/homeassistant/homeassistant/helpers/event.py", line 95, in state_change_listener
    event.data.get("new_state"),
  File "/usr/src/homeassistant/homeassistant/core.py", line 368, in async_run_job
    target(*args)
  File "/config/custom_components/average/sensor.py", line 194, in sensor_state_listener
    self._update_state()
  File "/config/custom_components/average/sensor.py", line 375, in _update_state
    self._update_period()
  File "/config/custom_components/average/sensor.py", line 357, in _update_period
    if start > now:
TypeError: '>' not supported between instances of 'NoneType' and 'datetime.datetime'

```

![Screenshot_20191011-044037](https://user-images.githubusercontent.com/14824890/66623359-2e653900-ebe3-11e9-8595-f30885340df1.png)

**Comment by mf-social** [comment]
Lol, no worries :)
