### ISSUE TITLE
2021.6 Dev release error....

### ISSUE THREAD

**Issue by DavidFW1960** [Limych/ha-average#65]
**Environment**

- Home Assistant Core release with the issue: 2021.6.0.dev20210525
- This custom component release with the issue: latest
- Last working this custom component release (if known): none in this dev release
- Operating environment (Home Assistant/Supervisor/Docker/venv): Supervised

**Describe the bug**

**Configuration.yaml**
```
  - platform: average
    name: today_temp_bom
    entities:
      - sensor.brisbane_temp
    start: '{{ now().replace(hour=0).replace(minute=0).replace(second=0) }}'
    end: '{{ now() }}'
```

**Steps to Reproduce**

**Expected behavior**

**Debug log**

```
Logger: homeassistant.config
Source: custom_components/average/sensor.py:23
Integration: average (documentation, issues)
First occurred: 12:48:37 PM (1 occurrences)
Last logged: 12:48:37 PM

Platform error: sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config.py", line 853, in async_process_component_config
    platform = p_integration.get_platform(domain)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 472, in get_platform
    cache[full_name] = self._import_platform(platform_name)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 477, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
  File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/config/custom_components/average/sensor.py", line 23, in <module>
    from homeassistant.components.history import LazyState
ImportError: cannot import name 'LazyState' from 'homeassistant.components.history' (/usr/src/homeassistant/homeassistant/components/history/__init__.py)
```

**Additional context**

**Comment by DavidFW1960** [comment]
ok the official beta 0 for 2021.6 also has this error

**Comment by Limych** [comment]
Opened issue to fix compatibility of HA code: https://github.com/home-assistant/core/issues/51140
And, of course, I've add fix to my component soon.

**Comment by DavidFW1960** [comment]
With updated component seeing these warnings:
```
2021-05-28 09:45:35 WARNING (SyncWorker_0) [homeassistant.components.history] state_changes_during_period was called from average, this is a deprecated function. Use homeassistant.components.recorder.history.state_changes_during_period instead, please report this to the maintainer of average
2021-05-28 09:45:35 WARNING (SyncWorker_0) [homeassistant.components.history] get_state was called from average, this is a deprecated function. Use homeassistant.components.recorder.history.get_state instead, please report this to the maintainer of average
```
Is this what the HA PR referenced is supposed to fix?
