### ISSUE TITLE
HA 2021.6 error on LazyState

### ISSUE THREAD

**Issue by Mariusthvdb** [Limych/ha-average#66]
**Environment**

- Home Assistant Core release with the issue: 2021.6 b
- This custom component release with the issue: 1.7.3
- Last working this custom component release (if known): on 2021.5
- Operating environment (Home Assistant/Supervisor/Docker/venv): HA OS

**Describe the bug**

**Configuration.yaml**
```yaml
  - platform: average
    name: Mean indoor measured temp
    entities:
      - sensor.temperatuur_living
      - sensor.dining_table_sensor_temperature
      - sensor.auditorium_sensor_temperature
      - etcetc
```

**Steps to Reproduce**

**Expected behavior**

**Debug log**

```text

2021-05-27 15:11:17 ERROR (MainThread) [homeassistant.config] Platform error: sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config.py", line 853, in async_process_component_config
    platform = p_integration.get_platform(domain)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 472, in get_platform
    cache[full_name] = self._import_platform(platform_name)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 477, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
  File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/config/custom_components/average/sensor.py", line 23, in <module>
    from homeassistant.components.history import LazyState
ImportError: cannot import name 'LazyState' from 'homeassistant.components.history' (/usr/src/homeassistant/homeassistant/components/history/__init__.py)

```

**Additional context**

Edit: now see this https://github.com/home-assistant/core/issues/51140 and PR to fix that https://github.com/home-assistant/core/pull/51144

so guess not a CC issue, but core... feel free to close.

**Comment by Limych** [comment]
Please upgrade to latest component version.
