### ISSUE TITLE
The sensor does not work in HA 2021.7.3

### ISSUE THREAD

**Issue by dzianiwonsacze** [Limych/ha-average#80]
**Environment**

- Home Assistant Core release with the issue:
- 2021.7.3
- This custom component release with the issue:
- 2.1.0
- Last working this custom component release (if known):
- 2021.6.6
- Operating environment (Home Assistant/Supervisor/Docker/venv):
- HASS OS

**Describe the bug**
The component does not work. Instead of calculating the average of sensors, it is listed as unavailable. The system does not report any issues setting it up though, as it sometimes does.

**Configuration.yaml**
```yaml

  - platform: average
    name: "AvLux"
    duration:
      minutes: 10
    entities:
      - sensor.sofa_lux_illuminance_lux
      - sensor.bedroom_lux_illuminance_lux
      - sensor.kitchen_lux_illuminance_lux

```

**Steps to Reproduce**
No steps necessary

**Expected behavior**
It would calculate the number and show in Lovelace

**Debug log**

2021-07-17 18:34:05 ERROR (MainThread) [homeassistant.helpers.entity] Update for sensor.avkitchlux fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 401, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 609, in async_device_update
    raise exc
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/homeassistant/homeassistant/util/__init__.py", line 280, in wrapper
    result = method(*args, **kwargs)
  File "/config/custom_components/average/sensor.py", line 327, in update
    self._update_state()
  File "/config/custom_components/average/sensor.py", line 499, in _update_state
    history_list = history.state_changes_during_period(
  File "/usr/src/homeassistant/homeassistant/components/recorder/history.py", line 142, in state_changes_during_period
    with session_scope(hass=hass) as session:
  File "/usr/local/lib/python3.9/contextlib.py", line 117, in __enter__
    return next(self.gen)
  File "/usr/src/homeassistant/homeassistant/components/recorder/util.py", line 57, in session_scope
    session = hass.data[DATA_INSTANCE].get_session()
TypeError: 'NoneType' object is not callable

Add your logs here.

```

**Additional context**
<!--
  Add any other context about the problem here.
-->

**Comment by Limych** [comment]
A new version of the component has now been released. Please update to the latest version of HA and the latest version of the component. Most likely, your bug will go away by itself.

**Comment by dzianiwonsacze** [comment]
Sadly, it did not. Please have a look below:

Logger: homeassistant.helpers.entity
Source: components/recorder/util.py:57
First occurred: 4:16:31 PM (176 occurrences)
Last logged: 4:37:31 PM

Update for sensor.avkitchlux fails
Update for sensor.avbedlux fails
Update for sensor.avsoflux fails
Update for sensor.avlux fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 446, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 654, in async_device_update
    raise exc
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/homeassistant/homeassistant/util/__init__.py", line 277, in wrapper
    result = method(*args, **kwargs)
  File "/config/custom_components/average/sensor.py", line 305, in update
    self._update_state()
  File "/config/custom_components/average/sensor.py", line 477, in _update_state
    history_list = history.state_changes_during_period(
  File "/usr/src/homeassistant/homeassistant/components/recorder/history.py", line 142, in state_changes_during_period
    with session_scope(hass=hass) as session:
  File "/usr/local/lib/python3.9/contextlib.py", line 117, in __enter__
    return next(self.gen)
  File "/usr/src/homeassistant/homeassistant/components/recorder/util.py", line 57, in session_scope
    session = hass.data[DATA_INSTANCE].get_session()
TypeError: 'NoneType' object is not callable

**Comment by dzianiwonsacze** [comment]
Oh, and I updated both - running 2021.8.8 and latest version of your component.

**Comment by dzianiwonsacze** [comment]
Ok, found the reason for the sensor not working - my password for MariaDB contained a @ symbol, and caused issues with accessing the database. Average sensor is working fine now, sorry for false alarm.
